export enum CHARACTER_ACTION {
  FETCH_CHARACTERS = 'CHARACTER_ACTION/FETCH_CHARACTERS',
  FETCH_CHARACTERS_SUCCESS = 'CHARACTER_ACTION/FETCH_CHARACTERS_SUCCESS',
  FETCH_CHARACTERS_ERROR = 'CHARACTER_ACTION/FETCH_CHARACTERS_ERROR',
  INIT_CHARACTERS = 'CHARACTER_ACTION/INIT_CHARACTERS',
}
